pipeline {
  agent any
  tools {
    nodejs '13.11.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    stage('Json Processing'){
      steps {
        
        def json = new JsonSlurper().parseText('{"nombre": "Alejo"}')
        def bodyText = json.body

        // Check if Pull Request body has certain text
        if ( bodyText.find('Alejo') ) {
            println 'Found Alejo user'
        }
      }
    }
  }
}
