pipeline {
  agent any
  tools {
    nodejs 'node-11.0.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    
    stage('JSON') {
      steps {
        script {
          def props = readJSON text: '{ "key": null, "a": "b" }', returnPojo: true
          assert props['key'] == null
          props.each { key, value ->
              echo "Walked through key $key and value $value"
          }
        }
      }
    }
    
    
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
  }
}
